CREATE TABLE IF NOT EXISTS notas_credito (
    id                          BIGINT,
    emissao_dia                 DATE,   
    emitente_ug                 VARCHAR,
    emitente_ug_descricao       VARCHAR,
    favorecido_doc              VARCHAR,
    favorecido_doc_descricao    VARCHAR,
    ro_evento                   VARCHAR,
    descricao_evento            VARCHAR,
    ptres                       VARCHAR,
    numero_nc                   VARCHAR,
    plano_interno               VARCHAR,
    plano_interno_descricao     VARCHAR,
    natureza_despeza            VARCHAR,
    ce                          VARCHAR,
    natureza_despeza_descricao  VARCHAR,
    fonte_recurso               VARCHAR,
    fonte_recurso_descricao     VARCHAR,
    siafi                       VARCHAR,
    esfera_orcamentaria         VARCHAR,
    valor_absoluto              DECIMAL(18,2),
    observacao                  VARCHAR,
    lancado_por                 VARCHAR
);